Finanse-aspnet-mvc/Models/Categories/Category.cs
using System.Collections.Generic;

namespace Finanse_aspnet_mvc.Models.Categories {
    public class Category : CategoryBase {
        public virtual ICollection<SubCategory> SubCategories { get; set; } = new List<SubCategory>();
    }
}

Finanse-aspnet-mvc/Models/Categories/CategoryBase.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Configuration;

namespace Finanse_aspnet_mvc.Models.Categories {
    [Table("Categories")]
    public abstract class CategoryBase: ICategoryBase {
        public int Id { get; set; }

        [StringLength(32)]
        [Required(AllowEmptyStrings = false)]
        public string Name { get; set; }
        public string ColorKey { get; set; }
        public string IconKey { get; set; }
        public bool VisibleInIncomes { get; set; }
        public bool VisibleInExpenses { get; set; }
        public bool CantDelete { get; set; } = false;
        [Required]
        public string UserId { get; set; }

        private string _lastColorKey;
        private string _color;
        public string Color {
            get {
                if (_lastColorKey == ColorKey && !string.IsNullOrEmpty(_color))
                    return _color;
                return _color = ConfigurationManager.AppSettings[_lastColorKey = ColorKey];
            }
        }

        private string _lastIconKey;
        private string _icon;
        public string Icon {
            get {
                if (_lastIconKey == IconKey && !string.IsNullOrEmpty(_icon))
                    return _icon;
                return _icon = ConfigurationManager.AppSettings[_lastIconKey = IconKey];
            }
        }
    }
}

Finanse-aspnet-mvc/Models/Categories/CategoryPost.cs
using System.ComponentModel.DataAnnotations;

namespace Finanse_aspnet_mvc.Models.Categories {
    public class CategoryPost : ICategoryBase {
        public int Id { get; set; }
        public string Name { get; set; }
        public string ColorKey { get; set; }
        public string IconKey { get; set; }
        [Display(Name = "Widoczna we wpływach")]
        public bool VisibleInIncomes { get; set; }
        [Display(Name = "Widoczna w wydatkach")]
        public bool VisibleInExpenses { get; set; }
        public bool CantDelete { get; set; }
        public int? ParentCategoryId { get; set; }
        [Required]
        public string UserId { get; set; }

        public CategoryBase GetCategory() {
            CategoryBase category;

            if (ParentCategoryId.HasValue && ParentCategoryId.Value != -1)
                category = new SubCategory {
                    ParentCategoryId = ParentCategoryId.Value
                };
            else
                category = new Category();

            category.Id = Id;
            category.Name = Name;
            category.ColorKey = ColorKey;
            category.IconKey = IconKey;
            category.VisibleInIncomes = VisibleInIncomes;
            category.VisibleInExpenses = VisibleInExpenses;
            category.CantDelete = CantDelete;
            category.UserId = UserId;

            return category;
        }
    }
}

Finanse-aspnet-mvc/Models/Categories/ICategoryBase.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Finanse_aspnet_mvc.Models.Categories {
    public interface ICategoryBase : ISpecificUserData {
        int Id { get; set; }
        string Name { get; set; }
        string ColorKey { get; set; }
        string IconKey { get; set; }
        bool VisibleInIncomes { get; set; }
        bool VisibleInExpenses { get; set; }
        bool CantDelete { get; set; }
    }
}

Finanse-aspnet-mvc/Models/Categories/ISubCategory.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Finanse_aspnet_mvc.Models.Categories {
    interface ISubCategory : ICategoryBase {
        int ParentCategoryId { get; set; }
    }
}

Finanse-aspnet-mvc/Models/Categories/SubCategory.cs
namespace Finanse_aspnet_mvc.Models.Categories {
    public class SubCategory : CategoryBase, ISubCategory {
        public int ParentCategoryId { get; set; }
        public virtual Category ParentCategory { get; set; }
        public Category AsCategory() {
            return new Category {
                Id = Id,
                Name = Name,
                ColorKey = ColorKey,
                IconKey = IconKey,
                VisibleInExpenses = VisibleInExpenses,
                VisibleInIncomes = VisibleInIncomes,
                CantDelete = CantDelete
            };
        }
    }
}

Finanse-aspnet-mvc/Controllers/CategoriesController.cs
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;
using Finanse_aspnet_mvc.Models;
using Finanse_aspnet_mvc.Models.Categories;
using Finanse_aspnet_mvc.Models.Helpers;
using Microsoft.AspNet.Identity;

namespace Finanse_aspnet_mvc.Controllers {
    [Authorize]
    public class CategoriesController : Controller {
        private readonly StackMoneyDb _db = new StackMoneyDb();
        private IEnumerable<KeyValuePair<string, string>> _colors;

        // GET: Categories
        public async Task<ActionResult> Index() {
            var model = new ExpensesAndIncomesViewModel {
                Expenses = await _db.Categories.Where(c => c.VisibleInExpenses).OrderBy(c => c.Name).ToListAsync(),
                Incomes = await _db.Categories.Where(c => c.VisibleInIncomes).OrderBy(c => c.Name).ToListAsync()
            };

            return View(model);
        }

        // GET: Categories/Details/5
        public ActionResult Details(int id) {
            return PartialView("_Details");
        }

        // GET: Categories/Create
        public ActionResult Create() {
            ViewBag.Colors = _colors ?? (_colors = AppSettingsHelper.GetColors());
            return PartialView("_Create");
        }

        // POST: Categories/Create
        [HttpPost]
        public async Task<ActionResult> Create(CategoryPost categoryPost) {
            var errors = ModelState.Values.SelectMany(v => v.Errors);

            ModelState.Remove(nameof(CategoryPost.CantDelete));
            ModelState.Remove(nameof(CategoryPost.UserId));

            if (ModelState.IsValid) {
                var category = categoryPost.GetCategory();
                category.UserId = User.Identity.GetUserId();

                _db.CategoriesAndSubCategories.Add(category);
                await _db.SaveChangesAsync();

                return Json(new { success = true });
            }

            return PartialView("_Create", categoryPost);
        }

        // GET: Categories/Edit/5
        public async Task<ActionResult> Edit(int id) {
            ViewBag.Colors = _colors ?? (_colors = AppSettingsHelper.GetColors());
            var model = await _db.CategoriesAndSubCategories.FindAsync(id);
            return PartialView("_Edit", model);
        }

        // POST: Categories/Edit/5
        [HttpPost]
        public async Task<ActionResult> Edit(SubCategory category) {
            if (ModelState.IsValid) {
                var newCategory = ConvertToRightCategoryType(category);
                _db.Entry(newCategory).State = EntityState.Modified;
                await _db.SaveChangesAsync();
                return Json(new { success = true });
            }
            return PartialView("_Edit", category);
        }

        // GET: Categories/Delete/5
        public async  Task<ActionResult> Delete(int? id) {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var category = await _db.CategoriesAndSubCategories.FindAsync(id);

            if (category == null)
                return HttpNotFound();

            return PartialView("_Delete", category);
        }

        // POST: Categories/Delete/5
        [HttpPost]
        public async Task<ActionResult> Delete(int id) {
            var category = await _db.CategoriesAndSubCategories.FindAsync(id);

            if (category == null)
                return HttpNotFound();

            _db.CategoriesAndSubCategories.Remove(category);
            await _db.SaveChangesAsync();
            return Json(new { success = true });
        }

        private static CategoryBase ConvertToRightCategoryType(SubCategory category) {
            if (category.ParentCategoryId == 0)
                return category.AsCategory();
            return category;
        }

        protected override void Dispose(bool disposing) {
            if (disposing)
                _db.Dispose();
            base.Dispose(disposing);
        }
    }

    public class ExpensesAndIncomesViewModel{
        public List<Category> Expenses { get; set; }
        public List<Category> Incomes { get; set; }
    }
}

Finanse-aspnet-mvc/Controllers/OperationsController.cs
using System;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;
using Finanse_aspnet_mvc.Models;
using Finanse_aspnet_mvc.Models.Helpers;
using Finanse_aspnet_mvc.Models.Operations;
using Microsoft.AspNet.Identity;
using System.Collections.Generic;
using Finanse_aspnet_mvc.Models.Categories;
using WebGrease.Css.Extensions;

namespace Finanse_aspnet_mvc.Controllers {
    [Authorize]
    public class OperationsController : Controller {
        private readonly StackMoneyDb _db = new StackMoneyDb();
        //private Operation[] _operations = new Operation[10];

        private IQueryable<Operation> OperationsOfLoginUser()
        {
            var userId = User.Identity.GetUserId();
            return _db.Operations.Where(o => o.UserId.Equals(userId));
        }

        // GET: Operations
        public async Task<ActionResult> Index(int? lastId, int? actualYear, int? actualMonth, string[] accounts, string groupBy) {
            if (!Request.IsAjaxRequest()) {
                ViewBag.Accounts = await _db.Accounts.ToListAsync();
                return View();
            }

            var actualMonthString = $"{actualYear}.{actualMonth:00}";

            var operationsOfThisMonth = OperationsOfLoginUser()
                .Where(o => o.Date.StartsWith(actualMonthString));     // because Data format is always YYYY.MM.DD
            
            /* Filter */
            if (accounts != null && accounts.Any()) {
                var accountsInt = Array.ConvertAll(accounts, int.Parse);
                operationsOfThisMonth = operationsOfThisMonth.Where(o => accountsInt.Contains(o.AccountId));
            }
            
            IEnumerable<IGrouping<string, Operation>> groupedOperations;
            switch (groupBy) {
                case "category":
                    groupedOperations = await OperationsByCategory(operationsOfThisMonth, lastId);
                    break;
                default:
                    groupedOperations = await OperationsByDate(operationsOfThisMonth, lastId);
                    break;
            }

            var result = new {
                lastId = groupedOperations.LastOrDefault()?.LastOrDefault()?.Id,
                partialView = RenderRazorViewToString("_OperationsList", groupedOperations)
            };

            return Content(JsonHelper.ToJsonString(result), "application/json");
        }

        private static async Task<IEnumerable<IGrouping<string, Operation>>> OperationsByDate(IQueryable<Operation> list, int? lastId)
        {
            var operationsOfThisMonthList = await list
                .OrderByDescending(o => o.Date)
                .ThenByDescending(o => o.Id)
                .ToListAsync();

            return TakePartOfOperations(operationsOfThisMonthList, lastId)
                .GroupBy(o => o.Date);
        }

        private static async Task<IEnumerable<IGrouping<string, Operation>>> OperationsByCategory(IQueryable<Operation> list, int? lastId)
        {
            var operationsOfThisMonthList = await list
                .OrderBy(o => o.Category is SubCategory
                    ? (o.Category as SubCategory).ParentCategory.Name
                    : o.Category.Name)
                .ThenByDescending(o => o.Date)
                .ThenByDescending(o => o.Id)
                .ToListAsync();

            return TakePartOfOperations(operationsOfThisMonthList, lastId)
                    .GroupBy(o => o.Category is SubCategory
                        ? ((SubCategory)o.Category).ParentCategory.Name
                        : o.Category.Name);
        }

        private static IEnumerable<Operation> TakePartOfOperations(IEnumerable<Operation> list, int? lastId) {
            return list
                .SkipWhile(o => lastId != null && o.Id != lastId)                   // skip while lastId is not equal actual id and there is lastId (!= -1)
                .Skip(lastId == null ? 0 : 1)                                       // if there is no lastId (== -1) then skip 0
                .Take(10);
        }

        public string RenderRazorViewToString(string viewName, object model) {
            var viewData = new ViewDataDictionary {
                Model = model
            };
            using (var sw = new StringWriter()) {
                var viewResult = ViewEngines.Engines.FindPartialView(ControllerContext, viewName);
                var viewContext = new ViewContext(ControllerContext, viewResult.View, viewData, TempData, sw);
                viewResult.View.Render(viewContext, sw);
                viewResult.ViewEngine.ReleaseView(ControllerContext, viewResult.View);
                return sw.GetStringBuilder().ToString();
            }
        }

        // GET: Operations/Details/5
        public async Task<ActionResult> Details(int? id) {
            if (!Request.IsAjaxRequest())
                return View("Index");

            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var operation = await _db.Operations.FindAsync(id);
            if (operation == null)
                return HttpNotFound();

            return PartialView("_Details", operation);
        }

        // GET: Operations/Create
        public ActionResult Create() {
            return PartialView("_Create");
        }

        // POST: Operations/Create
        [HttpPost]
        public async Task<ActionResult> Create(Operation operation) {

            ModelState.Remove(nameof(Operation.UserId));
            operation.UserId = User.Identity.GetUserId();

            if (ModelState.IsValid) {
                _db.Operations.Add(operation);
                await _db.SaveChangesAsync();
                return Json(new { success = true });
            }
            return PartialView("_Create", operation);
        }

        // GET: Operations/Edit/5
        public async Task<ActionResult> Edit(int? id) {
            if (!Request.IsAjaxRequest())
                return View("Index");

            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var operation = await _db.Operations.FindAsync(id);
            if (operation == null || !operation.UserId.Equals(User.Identity.GetUserId()))
                return HttpNotFound();

            return PartialView("_Edit", operation);
        }

        // POST: Operations/Edit/5
        [HttpPost]
        public async Task<ActionResult> Edit(Operation operation) {
            if (ModelState.IsValid) {
                _db.Entry(operation).State = EntityState.Modified;
                await _db.SaveChangesAsync();
                return Json(new { success = true });
            }
            return PartialView("_Edit", operation);
        }

        // GET: Operations/Delete/5
        public async Task<ActionResult> Delete(int? id) {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var operation = await _db.Operations.FindAsync(id);
            if (operation == null)
                return HttpNotFound();

            return PartialView("_Delete", operation);
        }

        // POST: Operations/Delete/5
        [HttpPost]
        public async Task<ActionResult> Delete(int id) {
            var operation = await _db.Operations.FindAsync(id);

            if (operation == null)
                return HttpNotFound();

            _db.Operations.Remove(operation);
            await _db.SaveChangesAsync();
            return Json(new { success = true });
        }

        protected override void Dispose(bool disposing) {
            if (disposing)
                _db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Finanse-aspnet-mvc/Views/Categories/Create.cshtml
@using Finanse_aspnet_mvc.Models
@model Finanse_aspnet_mvc.Models.Categories.SubCategory

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Category</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ColorKey, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ColorKey, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ColorKey, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IconKey, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IconKey, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IconKey, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VisibleInIncomes, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.VisibleInIncomes)
                    @Html.ValidationMessageFor(model => model.VisibleInIncomes, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VisibleInExpenses, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.VisibleInExpenses)
                    @Html.ValidationMessageFor(model => model.VisibleInExpenses, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Kategoria nadrzędna", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.ParentCategoryId, new List<SelectListItem>{new SelectListItem{Value = "0"}}.Concat(StackMoneyDb.OnlyCategoriesList().Select(i => new SelectListItem{Value = i.Id.ToString(), Text = i.Name })), new { @class = "btn btn-default" })
            </div>
        </div>
        
        @Html.HiddenFor(item => item.CantDelete)

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Finanse-aspnet-mvc/Views/Categories/Index.cshtml
@model Finanse_aspnet_mvc.Controllers.ExpensesAndIncomesViewModel

@{
    ViewBag.Title = "Kategorie";
}

@*<div style="margin: 16px;">
    <i class="fa fa-tags" style="font-size: 24px"></i>
    <h2 style="display: inline; margin-left: 16px; font-weight: lighter">Kategorie</h2>
</div>
<hr />*@

<!-- The Modal -->
<div id="pop-up" class="pop-up">
    <div class="pop-up-content">
        <!-- Modal content -->
        <div id="pop-up-content"></div>
    </div>
</div>


@*@Html.ActionLink("+", "Create", "Operations", null, new { data_modal = "", id = "btnCreate", @class = "btn btn-success btn-circle btn-lg button-add animate-button" })*@
<div class="page-content-new">
    <div class="page-top">
        <p class="page-title">Kategorie</p>
        <div class="flex-right">
            @Html.ActionLink("Dodaj nową", "Create", null, new { dataModal = "", id = "btnCreate", @class = "button-round animate-button" })
        </div>
    </div>
    <div class="multi-cards-container">
        <div class="page-card" style="flex: 1">
            <div class="header">
                <p>Wydatki</p>

                <button class="flex-right expand-button">
                    <i class="fa fa-angle-down animate-button" aria-hidden="true"></i>
                </button>
            </div>
            <div class="content">
                <div class="list">
                    @foreach (var item in Model.Expenses)
                    {
                        @Html.Partial("_Category", item)
                    }
                </div>
            </div>
        </div>

        <div class="page-card" style="flex: 1">
            <div class="header">
                <p>Wpływy</p>

                <button class="flex-right expand-button">
                    <i class="fa fa-angle-down animate-button" aria-hidden="true"></i>
                </button>
            </div>
            <div class="content">
                <div class="list">
                    @foreach (var item in Model.Incomes)
                    {
                        @Html.Partial("_Category", item)
                    }
                </div>
            </div>
        </div>
    </div>
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/modalform")

    <script>
        /* Slide Toogle */
        $("div.page-card button.expand-button").click(function () {
            var arrow = $(this).find("i.fa");

            arrow.toggleClass("fa-rotate-90");

            $(this).parent().parent().find("div.content").slideToggle();
        });
    </script>
}

Finanse-aspnet-mvc/Views/Categories/_Category.cshtml
@model Finanse_aspnet_mvc.Models.Categories.Category
@*<li>
    <div>
        @Html.DisplayFor(modelItem => Model.Name)
        @if (!Model.CantDelete) {
            <div class="btn-group" data-toggle="buttons">
                <button type="button" class="btn button-round animate-button dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="1000" data-close-others="true">
                    <span class="caret"></span>
                </button>
                <ul class="dropdown-menu" role="menu">
                    <li>@Html.ActionLink("Edit", "Edit", "Categories", new { id = Model.Id }, new { data_modal = "" })</li>
                    <li>@Html.ActionLink("Delete", "Delete", "Categories", new { id = Model.Id }, new { data_modal = "" })</li>
                </ul>
            </div>
        }
        <ol>
            @foreach (var subCategory in Model.SubCategories) {
                @Html.Partial("_SubCategory", subCategory)
            }
        </ol>
    </div>
</li>*@

<div class="category animate-button">
    <div class="category-icon">
        <i class="@(Model.Icon)" aria-hidden="true" style="color: @Model.Color;"></i>
    </div>
    <div class="category-text">
        <p>@Model.Name</p>
    </div>
    @if (!Model.CantDelete) {
        <div class="btn-group" data-toggle="buttons">
            <button type="button" class="button-more animate-button dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="1000" data-close-others="true">
                <i class="fa fa-ellipsis-v" aria-hidden="true"></i>
            </button>
            <ul class="dropdown-menu" role="menu">
                <li>@Html.ActionLink("Edytuj", "Edit", new {id = Model.Id}, new {dataModal = ""})</li>
                <li>@Html.ActionLink("Usuń", "Delete", new {id = Model.Id}, new {dataModal = ""})</li>
                <li class="divider"></li>
                <li>@Html.ActionLink("Dodaj podkategorię", "Create", new { id = Model.Id }, new { dataModal = "" })</li>
            </ul>
        </div>
    }
</div>
<div class="subCategories-list">
    @foreach (var subCategory in Model.SubCategories) {
        @Html.Partial("_SubCategory", subCategory)
    }
</div>

Finanse-aspnet-mvc/Views/Categories/_Delete.cshtml
@using Finanse_aspnet_mvc.Models.Categories
@model CategoryBase

<div class="pop-up-body">
    <p>Czy na pewno chcesz usunąć <strong>@Model.Name</strong> ?</p>
    @if (Model is Category) {
        <p>Zostaną usunięte wszystkie podkategorie.</p>
    }
</div>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()

    <div class="pop-up-footer">
        <div class="button-block">
            <button class="pop-up-button" data-dismiss="modal">Anuluj</button>
            <input class="pop-up-button pop-up-button-danger" type="submit" value="Usuń" />
        </div>
    </div>
}

Finanse-aspnet-mvc/Views/Categories/_Edit.cshtml
@model Finanse_aspnet_mvc.Models.Categories.CategoryBase

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title" id="myModalLabel">Edit Person</h4>
</div>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()

    <div class="modal-body">
        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)

            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ColorKey, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ColorKey, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ColorKey, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.IconKey, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.IconKey, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.IconKey, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.VisibleInIncomes, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.VisibleInIncomes)
                        @Html.ValidationMessageFor(model => model.VisibleInIncomes, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.VisibleInExpenses, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.VisibleInExpenses)
                        @Html.ValidationMessageFor(model => model.VisibleInExpenses, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.CantDelete, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.CantDelete)
                        @Html.ValidationMessageFor(model => model.CantDelete, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    </div>

    <div class="modal-footer">
        <button class="btn" data-dismiss="modal">Cancel</button>
        <input class="btn btn-primary" type="submit" value="Save" />
    </div>
}

Finanse-aspnet-mvc/Views/Categories/_SubCategory.cshtml
@model Finanse_aspnet_mvc.Models.Categories.SubCategory
@*<li>
    @Html.DisplayFor(modelItem => Model.Name)
    <div class="btn-group" data-toggle="buttons">
        <button type="button" class="btn btn-sm button-round animate-button dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="1000" data-close-others="true">
            <span class="caret"></span>
        </button>
        <ul class="dropdown-menu" role="menu">
            <li>@Html.ActionLink("Edit", "Edit", "Categories", new { id = Model.Id }, new { data_modal = "" })</li>
            <li>@Html.ActionLink("Delete", "Delete", "Categories", new { id = Model.Id }, new { data_modal = "" })</li>
        </ul>
    </div>
</li>*@

<div class="category animate-button">
    <div class="dot"></div>
    <div class="category-icon icon-small">
        <i class="@(Model.Icon)" aria-hidden="true" style="color: @Model.Color;"></i>
    </div>
    <div class="category-text">
        <p>@Model.Name</p>
    </div>
    @if (!Model.CantDelete) {
        <div class="btn-group" data-toggle="buttons">
            <button type="button" class="button-more animate-button dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="1000" data-close-others="true">
                <i class="fa fa-ellipsis-v" aria-hidden="true"></i>
            </button>
            <ul class="dropdown-menu" role="menu">
                <li>@Html.ActionLink("Edytuj", "Edit", new {id = Model.Id}, new {dataModal = ""})</li>
                <li>@Html.ActionLink("Usuń", "Delete", new {id = Model.Id}, new {dataModal = ""})</li>
            </ul>
        </div>
    }
</div>