Finanse-aspnet-mvc/Models/Helpers/OperationsHelper.cs
using System.Collections.Generic;
using Finanse_aspnet_mvc.Models.Operations;
using Newtonsoft.Json;

namespace Finanse_aspnet_mvc.Models.Helpers {
    public class OperationsHelper {
        public static string ToJsonString(IEnumerable<Operation> operations) {
            var jsSettings = new JsonSerializerSettings {
                ReferenceLoopHandling = ReferenceLoopHandling.Ignore
            };
            return JsonConvert.SerializeObject(operations, Formatting.None, jsSettings);
        }
    }
}

Finanse-aspnet-mvc/Models/Operations/Operation.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Finanse_aspnet_mvc.Models.Operations {
    [Table("Operations")]
    public class Operation : OperationBase {
        [Display(Name = "Data")]
        public string Date { get; set; }
        [Display(Name = "Widoczna w statystykach")]
        public bool VisibleInStatistics { get; set; } = true;
    }
}

Finanse-aspnet-mvc/Models/Operations/OperationPattern.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace Finanse_aspnet_mvc.Models.Operations {
    [Table("Patterns")]
    public class OperationPattern : OperationBase { }
}

Finanse-aspnet-mvc/Controllers/AccountsController.cs
using System.Collections.Generic;
using System.Data.Entity;
using System.Threading.Tasks;
using System.Web.Mvc;
using Finanse_aspnet_mvc.Models;
using Finanse_aspnet_mvc.Models.Accounts;
using Finanse_aspnet_mvc.Models.Helpers;
using Microsoft.AspNet.Identity;

namespace Finanse_aspnet_mvc.Controllers {
    [Authorize]
    public class AccountsController : Controller {
        StackMoneyDb _db = new StackMoneyDb();
        private IEnumerable<KeyValuePair<string, string>> _colors;

        // GET: Accounts
        public async Task<ActionResult> Index() {
            var model = await _db.Accounts.ToListAsync();
            return View(model);
        }

        // GET: Accounts/Details/5
        public ActionResult Details(int id) {
            return View();
        }

        // GET: Accounts/Create
        public ActionResult Create() {
            ViewBag.Colors = _colors ?? (_colors = AppSettingsHelper.GetColors());
            return View();
        }

        // POST: Accounts/Create
        [HttpPost]
        public async Task<ActionResult> Create(AccountPost accountPost) {
            ModelState.Remove(nameof(AccountPost.UserId));

            if (ModelState.IsValid) {
                var account = accountPost.GetAccount();
                account.UserId = User.Identity.GetUserId();

                _db.AccountsAndSubAccounts.Add(account);
                await _db.SaveChangesAsync();

                return RedirectToAction("Index");
            }
            return View();
        }

        // GET: Accounts/Edit/5
        public ActionResult Edit(int id) {
            return View();
        }

        // POST: Accounts/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection) {
            try {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch {
                return View();
            }
        }

        // GET: Accounts/Delete/5
        public ActionResult Delete(int id) {
            return View();
        }

        // POST: Accounts/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection) {
            try {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch {
                return View();
            }
        }
    }
}

Finanse-aspnet-mvc/Controllers/CategoriesController.cs
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;
using Finanse_aspnet_mvc.Models;
using Finanse_aspnet_mvc.Models.Categories;
using Finanse_aspnet_mvc.Models.Helpers;
using Microsoft.AspNet.Identity;

namespace Finanse_aspnet_mvc.Controllers {
    [Authorize]
    public class CategoriesController : Controller {
        private readonly StackMoneyDb _db = new StackMoneyDb();
        private IEnumerable<KeyValuePair<string, string>> _colors;

        // GET: Categories
        public async Task<ActionResult> Index() {
            var model = new ExpensesAndIncomesViewModel {
                Expenses = await _db.Categories.Where(c => c.VisibleInExpenses).OrderBy(c => c.Name).ToListAsync(),
                Incomes = await _db.Categories.Where(c => c.VisibleInIncomes).OrderBy(c => c.Name).ToListAsync()
            };

            return View(model);
        }

        // GET: Categories/Details/5
        public ActionResult Details(int id) {
            return PartialView("_Details");
        }

        // GET: Categories/Create
        public ActionResult Create() {
            ViewBag.Colors = _colors ?? (_colors = AppSettingsHelper.GetColors());
            return PartialView("_Create");
        }

        // POST: Categories/Create
        [HttpPost]
        public async Task<ActionResult> Create(CategoryPost categoryPost) {
            var errors = ModelState.Values.SelectMany(v => v.Errors);

            ModelState.Remove(nameof(CategoryPost.CantDelete));
            ModelState.Remove(nameof(CategoryPost.UserId));

            if (ModelState.IsValid) {
                var category = categoryPost.GetCategory();
                category.UserId = User.Identity.GetUserId();

                _db.CategoriesAndSubCategories.Add(category);
                await _db.SaveChangesAsync();

                return Json(new { success = true });
            }

            return PartialView("_Create", categoryPost);
        }

        // GET: Categories/Edit/5
        public async Task<ActionResult> Edit(int id) {
            ViewBag.Colors = _colors ?? (_colors = AppSettingsHelper.GetColors());
            var model = await _db.CategoriesAndSubCategories.FindAsync(id);
            return PartialView("_Edit", model);
        }

        // POST: Categories/Edit/5
        [HttpPost]
        public async Task<ActionResult> Edit(SubCategory category) {
            if (ModelState.IsValid) {
                var newCategory = ConvertToRightCategoryType(category);
                _db.Entry(newCategory).State = EntityState.Modified;
                await _db.SaveChangesAsync();
                return Json(new { success = true });
            }
            return PartialView("_Edit", category);
        }

        // GET: Categories/Delete/5
        public async  Task<ActionResult> Delete(int? id) {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var category = await _db.CategoriesAndSubCategories.FindAsync(id);

            if (category == null)
                return HttpNotFound();

            return PartialView("_Delete", category);
        }

        // POST: Categories/Delete/5
        [HttpPost]
        public async Task<ActionResult> Delete(int id) {
            var category = await _db.CategoriesAndSubCategories.FindAsync(id);

            if (category == null)
                return HttpNotFound();

            _db.CategoriesAndSubCategories.Remove(category);
            await _db.SaveChangesAsync();
            return Json(new { success = true });
        }

        private static CategoryBase ConvertToRightCategoryType(SubCategory category) {
            if (category.ParentCategoryId == 0)
                return category.AsCategory();
            return category;
        }

        protected override void Dispose(bool disposing) {
            if (disposing)
                _db.Dispose();
            base.Dispose(disposing);
        }
    }

    public class ExpensesAndIncomesViewModel{
        public List<Category> Expenses { get; set; }
        public List<Category> Incomes { get; set; }
    }
}

Finanse-aspnet-mvc/Controllers/OperationsController.cs
using System;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;
using Finanse_aspnet_mvc.Models;
using Finanse_aspnet_mvc.Models.Helpers;
using Finanse_aspnet_mvc.Models.Operations;
using Microsoft.AspNet.Identity;
using System.Collections.Generic;
using Finanse_aspnet_mvc.Models.Categories;
using WebGrease.Css.Extensions;

namespace Finanse_aspnet_mvc.Controllers {
    [Authorize]
    public class OperationsController : Controller {
        private readonly StackMoneyDb _db = new StackMoneyDb();
        //private Operation[] _operations = new Operation[10];

        private IQueryable<Operation> OperationsOfLoginUser()
        {
            var userId = User.Identity.GetUserId();
            return _db.Operations.Where(o => o.UserId.Equals(userId));
        }

        // GET: Operations
        public async Task<ActionResult> Index(int? lastId, int? actualYear, int? actualMonth, string[] accounts, string groupBy) {
            if (!Request.IsAjaxRequest()) {
                ViewBag.Accounts = await _db.Accounts.ToListAsync();
                return View();
            }

            var actualMonthString = $"{actualYear}.{actualMonth:00}";

            var operationsOfThisMonth = OperationsOfLoginUser()
                .Where(o => o.Date.StartsWith(actualMonthString));     // because Data format is always YYYY.MM.DD
            
            /* Filter */
            if (accounts != null && accounts.Any()) {
                var accountsInt = Array.ConvertAll(accounts, int.Parse);
                operationsOfThisMonth = operationsOfThisMonth.Where(o => accountsInt.Contains(o.AccountId));
            }
            
            IEnumerable<IGrouping<string, Operation>> groupedOperations;
            switch (groupBy) {
                case "category":
                    groupedOperations = await OperationsByCategory(operationsOfThisMonth, lastId);
                    break;
                default:
                    groupedOperations = await OperationsByDate(operationsOfThisMonth, lastId);
                    break;
            }

            var result = new {
                lastId = groupedOperations.LastOrDefault()?.LastOrDefault()?.Id,
                partialView = RenderRazorViewToString("_OperationsList", groupedOperations)
            };

            return Content(JsonHelper.ToJsonString(result), "application/json");
        }

        private static async Task<IEnumerable<IGrouping<string, Operation>>> OperationsByDate(IQueryable<Operation> list, int? lastId)
        {
            var operationsOfThisMonthList = await list
                .OrderByDescending(o => o.Date)
                .ThenByDescending(o => o.Id)
                .ToListAsync();

            return TakePartOfOperations(operationsOfThisMonthList, lastId)
                .GroupBy(o => o.Date);
        }

        private static async Task<IEnumerable<IGrouping<string, Operation>>> OperationsByCategory(IQueryable<Operation> list, int? lastId)
        {
            var operationsOfThisMonthList = await list
                .OrderBy(o => o.Category is SubCategory
                    ? (o.Category as SubCategory).ParentCategory.Name
                    : o.Category.Name)
                .ThenByDescending(o => o.Date)
                .ThenByDescending(o => o.Id)
                .ToListAsync();

            return TakePartOfOperations(operationsOfThisMonthList, lastId)
                    .GroupBy(o => o.Category is SubCategory
                        ? ((SubCategory)o.Category).ParentCategory.Name
                        : o.Category.Name);
        }

        private static IEnumerable<Operation> TakePartOfOperations(IEnumerable<Operation> list, int? lastId) {
            return list
                .SkipWhile(o => lastId != null && o.Id != lastId)                   // skip while lastId is not equal actual id and there is lastId (!= -1)
                .Skip(lastId == null ? 0 : 1)                                       // if there is no lastId (== -1) then skip 0
                .Take(10);
        }

        public string RenderRazorViewToString(string viewName, object model) {
            var viewData = new ViewDataDictionary {
                Model = model
            };
            using (var sw = new StringWriter()) {
                var viewResult = ViewEngines.Engines.FindPartialView(ControllerContext, viewName);
                var viewContext = new ViewContext(ControllerContext, viewResult.View, viewData, TempData, sw);
                viewResult.View.Render(viewContext, sw);
                viewResult.ViewEngine.ReleaseView(ControllerContext, viewResult.View);
                return sw.GetStringBuilder().ToString();
            }
        }

        // GET: Operations/Details/5
        public async Task<ActionResult> Details(int? id) {
            if (!Request.IsAjaxRequest())
                return View("Index");

            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var operation = await _db.Operations.FindAsync(id);
            if (operation == null)
                return HttpNotFound();

            return PartialView("_Details", operation);
        }

        // GET: Operations/Create
        public ActionResult Create() {
            return PartialView("_Create");
        }

        // POST: Operations/Create
        [HttpPost]
        public async Task<ActionResult> Create(Operation operation) {

            ModelState.Remove(nameof(Operation.UserId));
            operation.UserId = User.Identity.GetUserId();

            if (ModelState.IsValid) {
                _db.Operations.Add(operation);
                await _db.SaveChangesAsync();
                return Json(new { success = true });
            }
            return PartialView("_Create", operation);
        }

        // GET: Operations/Edit/5
        public async Task<ActionResult> Edit(int? id) {
            if (!Request.IsAjaxRequest())
                return View("Index");

            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var operation = await _db.Operations.FindAsync(id);
            if (operation == null || !operation.UserId.Equals(User.Identity.GetUserId()))
                return HttpNotFound();

            return PartialView("_Edit", operation);
        }

        // POST: Operations/Edit/5
        [HttpPost]
        public async Task<ActionResult> Edit(Operation operation) {
            if (ModelState.IsValid) {
                _db.Entry(operation).State = EntityState.Modified;
                await _db.SaveChangesAsync();
                return Json(new { success = true });
            }
            return PartialView("_Edit", operation);
        }

        // GET: Operations/Delete/5
        public async Task<ActionResult> Delete(int? id) {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var operation = await _db.Operations.FindAsync(id);
            if (operation == null)
                return HttpNotFound();

            return PartialView("_Delete", operation);
        }

        // POST: Operations/Delete/5
        [HttpPost]
        public async Task<ActionResult> Delete(int id) {
            var operation = await _db.Operations.FindAsync(id);

            if (operation == null)
                return HttpNotFound();

            _db.Operations.Remove(operation);
            await _db.SaveChangesAsync();
            return Json(new { success = true });
        }

        protected override void Dispose(bool disposing) {
            if (disposing)
                _db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Finanse-aspnet-mvc/Controllers/PatternsController.cs
using System.Web.Mvc;

namespace Finanse_aspnet_mvc.Controllers {
    [Authorize]
    public class PatternsController : Controller {
        // GET: Patterns
        public ActionResult Index() {
            return View();
        }

        // GET: Patterns/Details/5
        public ActionResult Details(int id) {
            return View();
        }

        // GET: Patterns/Create
        public ActionResult Create() {
            return View();
        }

        // POST: Patterns/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection) {
            try {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch {
                return View();
            }
        }

        // GET: Patterns/Edit/5
        public ActionResult Edit(int id) {
            return View();
        }

        // POST: Patterns/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection) {
            try {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch {
                return View();
            }
        }

        // GET: Patterns/Delete/5
        public ActionResult Delete(int id) {
            return View();
        }

        // POST: Patterns/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection) {
            try {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch {
                return View();
            }
        }
    }
}

Finanse-aspnet-mvc/Views/Shared/_DeleteModal.cshtml
@model Finanse_aspnet_mvc.Models.ModalProperties

<!-- Modal -->
<div class="modal fade" id="@Model.ModalId" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
            @*<div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="myModalLabel">Confirm Delete</h4>
                    </div>*@
            <div class="modal-body">
                Czy na pewno chcesz usunąć <span><b>@Model.Model</b></span> ?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Zamknij</button>
                <input type="submit" value="Delete" class="btn btn-danger" />
            </div>
        </div>
    </div>
</div>

Finanse-aspnet-mvc/Views/Shared/_Layout.cshtml
@using Finanse_aspnet_mvc.Models.Helpers
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>StackMoney - @ViewBag.Title</title>
    @Styles.Render("~/Content/bootstrap.css")
    @Styles.Render("~/Content/reset.css")
    @Styles.Render("~/Content/css")
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    @Scripts.Render("~/bundles/modernizr")

</head>
<body class="body">
    @*<div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("StackMoney", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    @if (Request.IsAuthenticated) {
                        <ul class="nav navbar-nav">
                            <li>@Html.ActionLink("Kategorie", "Index", "Categories")</li>
                            <li>@Html.ActionLink("Statystyki", "Index", "Statistics")</li>
                            <li>@Html.ActionLink("Konta", "Index", "Accounts")</li>
                            <li>@Html.ActionLink("Szablony", "Index", "Patterns")</li>
                            <li>@Html.ActionLink("Zlecenia stałe", "Index", "StandingOrders")</li>
                            <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                        </ul>
                    }
                    @Html.Partial("_LoginPartial")
                </div>
            </div>
        </div>
        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - StackMoney</p>
            </footer>
        </div>*@

    <div id="wrapper" class="menuDisplayed">

        <!-- Sidebar -->
        <div id="sidebar-wrapper">

            <ul class="sidebar-nav">
                <li>
                    <a href="@Url.Action("Index", "Operations")" class="animate-button @Html.IsSelected("Index", "Operations", "active")">
                        <i class="fa fa-calendar-o"></i>
                        <span>Operacje</span>
                    </a>
                </li>
                <li>
                    <a href="@Url.Action("Index", "Categories")" class="animate-button @Html.IsSelected("Index", "Categories", "active")">
                        <i class="fa fa-tags"></i>
                        <span>Kategorie</span>
                    </a>
                </li>
                <li>
                    <a href="@Url.Action("Index", "Statistics")" class="animate-button @Html.IsSelected("Index", "Statistics", "active")">
                        <i class="fa fa-bar-chart"></i>
                        <span>Statystyki</span>
                    </a>
                </li>
                <li>
                    <a href="@Url.Action("Index", "Patterns")" class="animate-button @Html.IsSelected("Index", "Patterns", "active")">
                        <i class="fa fa-copy"></i>
                        <span>Szablony</span>
                    </a>
                </li>
                <li>
                    <a href="@Url.Action("Index", "Accounts")" class="animate-button @Html.IsSelected("Index", "Accounts", "active")">
                        <i class="fa fa-credit-card"></i>
                        <span>Konta</span>
                    </a>
                </li>
                <li>
                    <a href="@Url.Action("Index", "StandingOrders")" class="animate-button @Html.IsSelected("Index", "StandingOrders", "active")">
                        <i class="fa fa-clock-o"></i>
                        <span>Zlecenia stałe</span>
                    </a>
                </li>
                <li>
                    <a href="@Url.Action("Contact", "Home")" class="animate-button @Html.IsSelected("Contact", "Home", "active")">
                        <i class="fa fa-phone"></i>
                        <span>Kontakt</span>
                    </a>
                </li>
            </ul>

            @*<footer>
                <p>&copy; @DateTime.Now.Year</p>
                <p>StackMoney</p>
            </footer>*@
        </div>

        <!-- Page content -->
        <div id="page-content-wrapper">
            <div id="upper-bar">
                <button href="@Url.Action("Index", "Home")" id="sidebar-logo" class="animate-button sidebar-logo-wide"></button>

                <button href="#" id="button-hamburger" class="upper-bar-button animate-button">
                    <i class="fa fa-navicon"></i>
                </button>

                @*<input type="text" name="search" placeholder="Szukaj">*@

                <div class="container-1">
                    <span class="icon"><i class="fa fa-search"></i></span>
                    <input type="search" id="search" placeholder="Szukaj" />
                </div>

                @Html.Partial("_LoginPartial")
            </div>
            <div class="body-content">
                @RenderBody()
            </div>
        </div>
    </div>

    <!-- Menu toggle script -->

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

    <script>
        $("#button-hamburger").click(function (e) {
            e.preventDefault();
            $("#wrapper").toggleClass("menuDisplayed");

            $("#sidebar-logo").toggleClass("sidebar-logo-thin");
            $("#sidebar-logo").toggleClass("sidebar-logo-wide");
        });
    </script>
</body>
</html>

Finanse-aspnet-mvc/Views/Shared/_Operation.cshtml
@using Finanse_aspnet_mvc.Models.Categories
@model Finanse_aspnet_mvc.Models.Operations.Operation

<div class="operation animate-button">
    <div class="operation-icon">
        <i class="@(Model.Category.Icon)" aria-hidden="true" style="color: @Model.Category.Color;"></i>
    </div>

    <div class="operation-text">
        <p>@Model.TitleOrCategoryName</p>

        <div class="operation-category-name">
            @if (Model.Category is SubCategory) {
                <small>@(((SubCategory)Model.Category).ParentCategory.Name)</small>
                <i class="fa fa-chevron-right operation-angle"></i>
                <small>@Model.Category.Name</small>
            }
            else {
                <small>@Model.Category.Name</small>
            }
        </div>
    </div>

    <div class="operation-cost">
        @(Model.Cost.ToString()) PLN
    </div>

    @if (Model.IsExpense) {
        <i class="fa fa-arrow-left expense" aria-hidden="true"></i>
    }
    else {
        <i class="fa fa-arrow-left income" aria-hidden="true"></i>
    }

    @*<div class="btn-group" data-toggle="buttons">
            <button type="button" class="button-more animate-button dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="1000" data-close-others="true">
                <i class="fa fa-ellipsis-v" aria-hidden="true"></i>
            </button>
            <ul class="dropdown-menu" role="menu">
                <li>@Html.ActionLink("Szczegóły", "Details", "Operations", new { id = Model.Id }, new { data_modal = "" })</li>
                <li>@Html.ActionLink("Edytuj", "Edit", "Operations", new { id = Model.Id }, new { data_modal = "" })</li>
                <li class="divider"></li>
                <li>@Html.ActionLink("Usuń", "Delete", "Operations", new { id = Model.Id }, new { data_modal = "" })</li>
            </ul>
        </div>*@
</div>